#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : joblib
Version  : 1.0.0
Release  : 14
URL      : https://files.pythonhosted.org/packages/69/a1/68266edcfabe8dc240d7c9e06972a121b011b232f0d1796a016192438435/joblib-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/69/a1/68266edcfabe8dc240d7c9e06972a121b011b232f0d1796a016192438435/joblib-1.0.0.tar.gz
Summary  : Lightweight pipelining with Python functions
Group    : Development/Tools
License  : BSD-3-Clause
Requires: joblib-license = %{version}-%{release}
Requires: joblib-python = %{version}-%{release}
Requires: joblib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
|PyPi| |Azure| |Codecov|
.. |PyPi| image:: https://badge.fury.io/py/joblib.svg
:target: https://badge.fury.io/py/joblib
:alt: Joblib version

%package license
Summary: license components for the joblib package.
Group: Default

%description license
license components for the joblib package.


%package python
Summary: python components for the joblib package.
Group: Default
Requires: joblib-python3 = %{version}-%{release}

%description python
python components for the joblib package.


%package python3
Summary: python3 components for the joblib package.
Group: Default
Requires: python3-core
Provides: pypi(joblib)

%description python3
python3 components for the joblib package.


%prep
%setup -q -n joblib-1.0.0
cd %{_builddir}/joblib-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607962919
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/joblib
cp %{_builddir}/joblib-1.0.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/joblib/952b369f76c04f612e5ce4c5ea81eb088b42c2c3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/joblib/952b369f76c04f612e5ce4c5ea81eb088b42c2c3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
